import base64

s = "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAAAFVBMVEX///9Pq1n3/v8jHis1bmmsx1Z4QCjWmPiwAAAA0UlEQVR4nO3Yuw6DMBBFwbz//5PT4GYjy4tF8CLN6RCGO7Vvt2SPUPa7wwIAAFgGaIPP0GkQAACAcoDP1mkQAACAMoAsJAYAAHBdQByMRUCvaQgAAMAyQBy+h15bDdCe47nWbggAAMAyQG/4vRWf23B83/tuCAEAAFgGyA6PBrLnfiAAAACXBWQDAAAAAAAAuC7gXwEAANQHjC4eZ2v/BQAAqAfo3RceBRkOAwAAlAGMIFlQPJ8eBgAAKAPoQWbbPQwAAFAGECGzTQ8DAACcBfgCoeNiwfqOSL8AAAAASUVORK5CYII="
with open('food.png', 'rb') as f:
	print(base64.b64encode(f.read()).decode('ascii'))
# with open('food2.png', 'wb') as f:
# 	f.write(base64.b64decode(s))